disabled_rules:
  - force_cast
  - force_try
  - variable_name
  - type_name
  - file_length
  - line_length
  - type_body_length
  - implicit_getter
  - operator_whitespace
  - cyclomatic_complexity
  - function_body_length
  - control_statement
