language: objective-c

osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script: 'xcodebuild -workspace SwiftyJSON.xcworkspace -scheme "SwiftyJSON iOS" -destination "platform=iOS Simulator,name=iPhone 6" test'
